config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    
  }
  scope 'user/' do 
    get 'profile', to: 'users/manages#profile'
  end
  get 'assign_role', to: 'home#assign_role'
  root to: "home#index"


  resources :journeys
  resources :orders
  # get '/:traveller_id/orders/new', to: 'orders#new', as: "new_order"
  get 'traveller_list', to: 'users/manages#traveller_list'


end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :journeys, dependent: :destroy

  has_many :sender_orders, class_name: 'Order', foreign_key: :sender_id, dependent: :destroy
  has_many :traveller_orders, class_name: 'Order', foreign_key: :traveller_id, dependent: :destroy 

  def not_completed_journey
    self.journeys.find_by(status: "not_completed")
  end

  def completed_journeys
    self.journeys.where(status: "completed")
  end


  validates :firstname, :lastname, length: { minimum: 3, maximum: 15 }, presence: true
  validates :phone_no, :landline, length: { minimum:11, maximum:11 }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/manages_controller.rb
class Users::ManagesController < ApplicationController

    def profile
        render template: "users/show"
    end

    def traveller_list
        if params[:from].present? && params[:to].present? && params[:capacity].present?
            @journeys = Journey.search(params[:from], params[:to], params[:capacity])
            render "users/traveller_list"

        else
            flash.now[:alert] = "you'r missing some fields"
            render "users/traveller_list"
        end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :phone_no, :landline, :city, :state, :country])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :phone_no, :landline, :city, :state, :country, :role])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/_profile_section1.html.erb
<div class="card mb-4">
<div class="card-body text-center">
    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
    class="rounded-circle img-fluid" style="width: 150px;">
    <h5 class="my-3"><%=current_user.firstname%></h5>
    <p class="text-muted mb-1"><%=current_user.roles_name %></p>
    <p class="text-muted mb-4"><%= address(current_user.city, current_user.state, current_user.country) %></p>

    <div class="d-flex justify-content-center mb-2">
        <%= link_to "Edit", edit_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0 left-margin" %>
        <%= link_to "Delete Profile", user_registration_path, method: :delete, class: "btn btn-outline-danger my-2 my-sm-0 left-margin" %> 
    </div>
</div>
</div>

app/views/users/_profile_section2.html.erb
<div class="card mb-4 mb-lg-0">
<div class="card-body p-0">
    <ul class="list-group list-group-flush rounded-3">
    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <i class="fas fa-globe fa-lg text-warning"></i>
        <p class="mb-0">https://mdbootstrap.com</p>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <i class="fab fa-github fa-lg" style="color: #333333;"></i>
        <p class="mb-0">mdbootstrap</p>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
        <p class="mb-0">@mdbootstrap</p>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
        <p class="mb-0">mdbootstrap</p>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
        <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
        <p class="mb-0">mdbootstrap</p>
    </li>
    </ul>
</div>
</div>

app/views/users/_profile_section3.html.erb
<div class="card mb-4">
<div class="card-body">
    <div class="row">
    <div class="col-sm-3">
        <p class="mb-0">Full Name</p>
    </div>
    <div class="col-sm-9">
        <p class="text-muted mb-0"><%=full_name(current_user.firstname, current_user.lastname)%></p>
    </div>
    </div>
    <hr>
    <div class="row">
    <div class="col-sm-3">
        <p class="mb-0">Email</p>
    </div>
    <div class="col-sm-9">
        <p class="text-muted mb-0"><%=current_user.email%></p>
    </div>
    </div>
    <hr>
    <div class="row">
    <div class="col-sm-3">
        <p class="mb-0">Phone</p>
    </div>
    <div class="col-sm-9">
        <p class="text-muted mb-0"><%= current_user.phone_no%></p>
    </div>
    </div>
    <hr>
    <div class="row">
    <div class="col-sm-3">
        <p class="mb-0">Landline</p>
    </div>
    <div class="col-sm-9">
        <p class="text-muted mb-0"><%= current_user.landline%></p>
    </div>
    </div>
    <hr>
    <div class="row">
    <div class="col-sm-3">
        <p class="mb-0">Address</p>
    </div>
    <div class="col-sm-9">
        <p class="text-muted mb-0"><%= address(current_user.city, current_user.state, current_user.country) %></p>
    </div>
    </div>
</div>
</div>

app/views/users/_profile_section4.html.erb
<div class="col-md-12">
    <div class="card mb-4 mb-md-0">
    <div class="card-body">
        <p class="mb-4"><span class="text-primary font-italic me-1">assigment</span> Project Status
        </p>
        <p class="mb-1" style="font-size: .77rem;">Web Design</p>
        <div class="progress rounded" style="height: 5px;">
        <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80"
            aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <p class="mt-4 mb-1" style="font-size: .77rem;">Website Markup</p>
        <div class="progress rounded" style="height: 5px;">
        <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
            aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <p class="mt-4 mb-1" style="font-size: .77rem;">One Page</p>
        <div class="progress rounded" style="height: 5px;">
        <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
            aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <p class="mt-4 mb-1" style="font-size: .77rem;">Mobile Template</p>
        <div class="progress rounded" style="height: 5px;">
        <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
            aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <p class="mt-4 mb-1" style="font-size: .77rem;">Backend API</p>
        <div class="progress rounded mb-2" style="height: 5px;">
        <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
            aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <h1>sender#show</h1>
        <section style="background-color: #eee;">

        <div class="row">
        <div class="col-lg-4">
            <%= render "users/profile_section1" %>
            <%= render "users/profile_section2" %>            
        </div>
        <div class="col-lg-8">
            <%= render "users/profile_section3" %>            
            <div class="row">
                <%= render "users/profile_section4" %>            
            </div>
        </div>
        </div>
    </div>
    </section>
    
</div>

app/views/users/traveller_list.html.erb
<div class="container">
    <h1>Travellers</h1>
    
    <%= form_tag(traveller_list_path, method: :get, class: "form-inline my-2 my-lg-0")  do %>
        <%= text_field_tag :from, params[:from], placeholder: 'From', class: "form-control mr-sm-2" %> 
        <%= text_field_tag :to, params[:to], placeholder: 'To', class: "form-control mr-sm-2" %> 
        <%= text_field_tag :capacity, params[:capacity], placeholder: 'Capacity', class: "form-control mr-sm-2" %> 
        <%= submit_tag('Search', name: :nill, class: "btn btn-success my-2 my-sm-0") %>
    <%end%>
    </br>
    <% if @journeys %>
        <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">From</th>
                    <th scope="col">To</th>
                    <th scope="col">Traveller</th>
                    <th scope="col">Capacity</th>
                    <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @journeys.each do | journey | %>
                        <tr>
                            <th scope="row">1</th>
                            <td><%=journey.from%></td>
                            <td><%=journey.to%></td>
                            <td><%=journey.user.firstname%></td>
                            <td><%=journey.capacity%></td>
                            <td>
                                <%= form_tag(new_order_path, method: :get, class: "form-inline my-2 my-lg-0")  do %>
                                    <%= hidden_field_tag :traveller_id, journey.user_id %>
                                    <%= submit_tag('place an order', name: :nill, class: "btn btn-success my-2 my-sm-0") %>
                                <%end%>
                            </td>
                        </tr>                        
                    <%end%>
                </tbody>
            </table> 
    <% end %>
</div>