config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    
  }
  scope 'user/' do 
    get 'profile', to: 'users/manages#profile'
  end
  get 'assign_role', to: 'home#assign_role'
  root to: "home#index"


  resources :journeys
  resources :orders
  # get '/:traveller_id/orders/new', to: 'orders#new', as: "new_order"
  get 'traveller_list', to: 'users/manages#traveller_list'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index; end

    def assign_role
        current_user.add_role params[:role]
        redirect_to root_path
    end
end

app/views/home/index.html.erb
<div class="container text-center">
    <h1>Welcome to Delivery App, <%=current_user.firstname.capitalize%></h1>

    <% if current_user %>
        <% if !current_user.has_any_role? %>
            <h1>neither sender nor traveller</h1>
            <div class="container">
                <div class="d-flex p-2 align-items-center">
                    <%= form_tag(assign_role_path, method: :get, class: "form-inline my-2 my-lg-0")  do %>
                        <%= hidden_field_tag(:role, "traveller") %>
                        <%= submit_tag('Become Traveller', name: :nil, class: "btn btn-outline-dark my-2 my-sm-0") %>
                    <%end%> 
                    <%= form_tag(assign_role_path, method: :get, class: "form-inline my-2 my-lg-0")  do %>
                        <%= hidden_field_tag(:role, "sender") %>
                        <%= submit_tag('Become Sender', name: :nil, class: "btn btn-dark my-2 my-sm-0") %>
                    <%end%>
                </div>
            </div>
        <%elsif current_user.has_role? :sender %>
            <h1>You'r a sender</h1>
        <% elsif current_user.has_role? :traveller %>
            <h1>Traveller</h1>
            <% if !current_user.not_completed_journey.present? %>
                <%= link_to "New Journey", new_journey_path, class: "btn btn-outline-dark" %>
            <% end %> 
        <%end%>
    <% end %>
</div>