config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    
  }
  scope 'user/' do 
    get 'profile', to: 'users/manages#profile'
  end
  get 'assign_role', to: 'home#assign_role'
  root to: "home#index"


  resources :journeys
  resources :orders
  # get '/:traveller_id/orders/new', to: 'orders#new', as: "new_order"
  get 'traveller_list', to: 'users/manages#traveller_list'


end

app/models/order.rb
class Order < ApplicationRecord
  resourcify
  belongs_to :traveller, class_name: "User", foreign_key: "traveller_id"
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  has_many :items, inverse_of: :order, dependent: :destroy
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

  validates :receiver_address, length: {minimum:11, maximum:60}, presence: true
  validates :receiver_phone, length: {minimum:11, maximum:11}, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    # before_action :restrict_traveller_to_access_orders
    # before_action :cannot_access_the_other_senders_orders
    # before_action :set_user, only: [:new, :create, :edit, :update, :index]
    before_action :find_and_set_orders, only: [:show, :destroy]
    # load_and_authorize_resource

    def index
        # if current_user.has_role? :sender
        #     @orders = current_user.sender_orders
        # elsif current_user.has_role? :traveller
        #     @orders = current_user.traveller_orders
        # end
        @orders = (current_user.has_role? :sender) ? @orders = current_user.sender_orders : @orders = current_user.traveller_orders
        
        if can? :index, Order
            render :index
        else
            flash["alert"] = "Not authorized to access Order#index"
            redirect_to root_path
        end
    end

    def new 
        @order = current_user.sender_orders.build
        session[:traveller_id] = params[:traveller_id].to_i
        if can? :new, Order
            render :new
        else
            flash["alert"] = "Not authorized to access Order#new"
            redirect_to root_path
        end
    end

    def create
        if can? :create, Order
            traveller_id = session[:traveller_id]
            @order = Order.new(order_params)
            @order.traveller_id = traveller_id
            @order.sender_id = current_user.id
            if @order.save
                redirect_to orders_path, notice: "successfully created an order"
            else
                render "new"
            end
        else
            flash["alert"] = "Not authorized to access Order#create"
            redirect_to root_path
        end
    end

    def edit
        @order = current_user.sender_orders.find_by(id: params[:id])
        if (@order.present?) && (can? :edit, Order)
            render :edit
        else
            flash["alert"] = "Not authorized to access Order#edit"
            redirect_to root_path
        end
    end

    def update
        if can? :update, Order
            @order = current_user.sender_orders.find_by(id: params[:id])
            if @order.update(order_params)
                redirect_to orders_path, notice: "successfully updated!"
            else
                render "edit"
            end
        else
            flash["alert"] = "Not authorized to access Order#update"
            redirect_to root_path
        end

    end



    def show
        if (@order.present?) && (can? :show, Order)
            # render json: @order, include: [:items]
            render :show
        else
            flash["alert"] = "Not authorized to access Order#show"
            redirect_to root_path
        end
    end

    def destroy
        if can? :destroy, Order
            @order.destroy
            redirect_to orders_path
        else
            flash["alert"] = "Not authorized to access Order#destroy"
            redirect_to root_path
        end
    end

    private
    def order_params
        params.require(:order).permit(:receiver_name, :receiver_phone, :receiver_address, :traveller_id, items_attributes: [:id, :itemname, :_destroy])
    end

    def find_and_set_orders
        @order = (current_user.has_role? :sender) ? current_user.sender_orders.find_by(id: params[:id]) : current_user.traveller_orders.find_by(id: params[:id])
    end

    # def set_user
    #     @user = User.find_by(id: current_user.id)
    # end

    # def restrict_traveller_to_access_orders
    #     if current_user_credential.user_type == "Traveller"
    #         flash["alert"] = "you'r not authorised to access it."
    #         redirect_to root_path
    #     end
    # end

    # def cannot_access_the_other_senders_orders
    #     if current_user_credential.user_id != params[:sender_id].to_i
    #         flash["alert"] = "you can only access your own orders"
    #         redirect_to root_path
    #     end
    # end
end

app/views/orders/_form.html.erb
<div class="row">
    <div class="col-12">
        <%= form_with model: @order do |f| %>
        <% if @order.errors.any? %>
                <ul>
                    <% @order.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>
        <div class="form-group">
            <%= f.label :receiver_name %>
            <%= f.text_field :receiver_name, autofocus: true, autocomplete: 'receiver_name', class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :receiver_phone %>
            <%= f.number_field :receiver_phone, autocomplete: 'receiver_phone', class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :receiver_address %>
            <%= f.text_area :receiver_address, autocomplete: 'receiver_address', class: 'form-control' %>
        </div>

        <h3>Items</h3>
        <div id='items'>
            <%= f.fields_for :items do | item | %>
            <%= render 'item_fields', :f => item %>
            <% end %>
            <div class='links'>
            <%= link_to_add_association 'add item', f, :items, class: "btn btn-primary btn-sm" %>
            </div>
        </div>

        <div class="actions">
            <%= f.submit(@order.new_record? ? "Create" : "Update" , class: "btn btn-outline-success top-margin" )%>
        </div>
        <% end %>

    </div>
</div> 

app/views/orders/_item_fields.html.erb
<div class='nested-fields'>
    <div class="form-group">
        <%= f.label :Item, class: "text-monospace" %> 
        <%= f.text_field :itemname, class: 'form-control col-md-3' %>
        <%= link_to_remove_association "remove item", f, class: "btn btn-danger btn-sm" %>
    </div>
</div>

app/views/orders/edit.html.erb
<div class="container">
    <h1>order#edit</h1>
    <%= render "form" %>
</div>

app/views/orders/index.html.erb
<div class="container">
    <h1>order#index</h1>
    <table class="table table-bordered">
        <thead class="thead-dark">
            <tr>
            <th scope="col">#</th>
            <th scope="col">Sender</th>
            <th scope="col">Receiver</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <% @orders.each do | order | %>
                <tr>
                    <th scope="row">1</th>
                    <td><%=current_user.firstname%></td>
                    <td><%=order.receiver_name%></td>
                    <td>
                        <%= link_to "view", order_path(order), class: "btn btn-outline-info btn-sm"%>
                        <% if current_user.has_role? :sender %>
                            <%= link_to "edit", edit_order_path(order), class: "btn btn-outline-success btn-sm" %>
                            <%= link_to "delete", order_path(order), method: :delete, class: "btn btn-outline-danger btn-sm" %> 
                        <%end%>
                    </td>
                </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/orders/new.html.erb
<div class="container">
    <h1>order#new</h1>
    <%= render "form" %>
</div>

app/views/orders/show.html.erb
<div class="container">
        <p class="text-monospace">receiver's name : <%= @order.receiver_name %></p>
        <p class="text-monospace">receiver's phone : <%= @order.receiver_phone %></p>
        <p class="text-monospace">receiver's address : <%= @order.receiver_address %></p>
        <% @order.items.each do |item| %>
            <p class="text-monospace">item name : <%= item.itemname %></p>
        <%end%>
</div>