config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: 'users/sessions', 
    registrations: 'users/registrations',
    
  }
  scope 'user/' do 
    get 'profile', to: 'users/manages#profile'
  end
  get 'assign_role', to: 'home#assign_role'
  root to: "home#index"


  resources :journeys
  resources :orders
  # get '/:traveller_id/orders/new', to: 'orders#new', as: "new_order"
  get 'traveller_list', to: 'users/manages#traveller_list'


end

app/views/layouts/_errors.html.erb
<div class="container">
    <p class="notice alert-success alert-dismissible fade show"><%= notice %></p>
    <p class="alert alert-danger alert-dismissible fade show"><%= alert %></p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to "CourierPlease", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
                <% if current_user %>
                    <% if current_user.has_role? :traveller %>
                        <li class="nav-item active">
                            <%= link_to "Profile", profile_path, class: "nav-link" %>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Journey
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <% if current_user.not_completed_journey.present? %>
                                    <%= link_to "Current Journey", journey_path(current_user.not_completed_journey.id), class: "dropdown-item" %>
                                <% end %>
                                <% if current_user.completed_journeys.present? %>
                                    <%= link_to "History", journeys_path, class: "dropdown-item" %>
                                <% end %>
                            </div> 

                        </li>
                        <li class="nav-item">
                            <%= link_to "Orders", orders_path, class: "nav-link" %>
                        </li>
                    <% elsif current_user.has_role? :sender %>
                        <li class="nav-item active">
                            <%= link_to "Profile", profile_path, class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Travellers List", traveller_list_path, class: "nav-link" %>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Orders", orders_path, class: "nav-link" %>
                        </li>
                    <%end%>
                <% end %>
            </ul> 
            
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                <% if !current_user %>
                    <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0 left-margin" %>
                <%else%>
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger my-2 my-sm-0 left-margin" %>
                <%end%>
            </form>

        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MRPProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=  Rails.application.credentials.google[:maps] %>&libraries=places&callback=initMap" async defer data-turbolinks-eval="false"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/errors" if alert || notice %>
    <%= yield %>
  </body>
</html>